ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT  = /dev/ttyACM0
BOARD_TAG    = uno
MONITOR_PORT  = /dev/ttyACM0
ARDUINO_LIBS = SdFat SoftwareSerial UTFT_SPI ArduCAM
ARDMK_DIR = /usr/local
ARDMK_PATH = /usr/share/arduino
MONITOR_BAUDRATE = 19200
include /usr/share/arduino/Arduino.mk
