ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT  = /dev/ttyACM0
BOARD_TAG    = uno
MONITOR_PORT  = /dev/ttyACM0
ARDUINO_LIBS = Wire/utility SPI Wire SD SD/utility SoftwareSerial UTFT_SPI ArduCAM
ARDMK_DIR = /usr/local
ARDMK_PATH = /usr/share/arduino
MONITOR_BAUDRATE = 115200
include /usr/share/arduino/Arduino.mk
